### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by xamel** [david63/david63-cookiepolicy#12]
Hi,

thanks for your MOD.

I will activate the MOD and then I geht the following Fatal error message, I added also the missing language, but I get the same message.

`Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'You have requested a non-existent service "language".' in /var/www/web25983339/html/phpbb3/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php:806 Stack trace: #0 /var/www/web25983339/html/phpbb3/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php(444): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('language') #1 /var/www/web25983339/html/phpbb3/ext/david63/cookiepolicy/ext.php(33): Symfony\Component\DependencyInjection\ContainerBuilder->get('language') #2 /var/www/web25983339/html/phpbb3/includes/acp/acp_extensions.php(139): david63\cookiepolicy\ext->is_enableable() #3 /var/www/web25983339/html/phpbb3/includes/functions_module.php(674): acp_extensions->main('extensions', 'main') #4 /var/www/web25983339/html/phpbb3/adm/index.php(81): p_master->load_active() #5 {main} thrown in /var/www/web25983339/html/phpbb3/vendor/symfony/dependency-injection/Symfony/Component/DependencyInjection/ContainerBuilder.php on line 806`

Please check it

**Comment by david63** [comment]
That looks as if you are using the 3.2 version on a 3.1 board
